$.jStorage.set('language', {
	en : {
		tools : 'Tools',
		matadata : 'Metadata',
		the_beta : 'Try different knowledge graphs',
		the_graph : 'Enter keywords to search in the knowledge graph «',
		the_dbpedia : 'Easy navigation on the international knowledge bases Wikidata, DBpedia',
		the_start : 'Start the search \>\>',
		the_word : 'Type the words ...',
		the_type : 'Type',
		the_title : 'Title',
		the_url : 'URL',
		the_class : 'Class',
		the_comment : 'Commentary',
		the_keywords : 'Keywords',
		the_property : 'Priperty',
		the_resource : 'Enter resource URI',
		resource : 'Resource',
		no_classes : 'Classes not found',
		restart : 'Закрыть граф',
		generateInverse : 'Сгенерировать обратные отношения',
		autoExpand : 'Режим автоматического расширения',
		autoSameAs : 'Сгенерировать обратные отношения sameAs',
		autoCollectImages : 'Собирать изображения в ходе поиска',
		autoDrawMap : 'Ресурсы геолокации',
		noName : 'Не указано наименование',
		addUri : 'Insert an URI ...',
		findResource : 'Найти ресурсы',
		choose : 'choose ...',
		choose_class : 'choose entity class ...',
		resourceMissing : 'Ресурс не найден',
		resourceMissingDoc : 'Строковые данные или изображения не были обнаружены',
		options : 'ОПЦИИ',
		endpointNotConfigured : 'Для ресурса не сконфигурирована точка доступа',
		endpointNotConfiguredSoInternal : 'Для ресурса не сконфигурирована точка доступа, создание временного графа',
		impostaUnaURI : 'Задайте URI, сформируйте поисковый запрос или выберите один из предложенных примеров',
		example : 'Example',
		noIe : 'Internet Explorer не поддерживается.',
		enpointNotAvailable : 'Ошибка точки доступа',
		errorBox : 'Ошибка точки доступа',
		errorOntotext : 'Систематическая ошибка Ontotext GraphDB. Пожалуйста, попробуйте позже.',
		enpointNotAvailableOrSLow : 'Ошибка точки доступа или превышен лимит времени',
		imagesNotFound : 'Для ресурса не найдено изображений',
		mapNotFound : 'Для ресурса не найдено карт',
		propsNotFound : 'Ничего не найдено',
		propsFound : 'Найденные свойства',
		showResource : 'Подсветить ресурс',
		zoomIn : 'Увеличить',
		showConsole : 'Показать консоль (experimental)',
		executeThisQuery : 'Выполнить SPARQL-запрос в новом окне',
		moreInfoOnThis : 'Больше информации об этом ресурсе',
		ontotextSearch : 'Semantic Web',
		simpleSearch : 'DBpedia easy navigation',
		endPoint : 'Select endpoint',
		choose_graph : 'choose graph ...',
		ontotextSearchDescription : 'Облачная платформа Ontotext GraphDB и Семантический образовательный портал «Кафедра онлайн» предлагают вашему вниманию базу ядерных знаний, в которой можно осуществлять поиск ресурсов по ключевым словам.<br>Чтобы найти нужный ресурс, выберите граф знаний и начните вводить ключевое слово. Затем выберите подходящий ресурс из предложенного списка и нажмите "Начать поиск >>"',
		simpleSearchDescription : 'DBpedia есть крупнейшая международная база знаний, в которой можно осуществлять поиск ресурсов по ключевым словам.<br/><br/>Чтобы найти требуемый ресурс, в строке ввода наберите несколько первых букв ключевого слова. Затем выберите подходящий ресурс из предложенного списка и нажмите "Начать поиск >>"',
		insertUri : 'Simple URI search',
		insertUriDescription : 'Здесь возможно анализировать и отображать даже те RDF-ресурсы, которые по каким-либо причинам недоступны через SPARQL-запросы.<br/><br/>Указав URI произвольного RDF-ресурса, можно получить доступ к соответствующему контенту и исследовать его взаимосвязи.',
		insertData : 'Найти данные',
		centerClose : 'Сфокусироваться на ресурсе',
		openOnline : 'Онлайн доступ к ресурсу',
		openRelated : 'Посмотреть связанные ресурсы',
		removeResource : 'Удалить элемент',
		noImage:'Изображение не доступно',
		connectedResources:'связанных ресурсов',
		ontotext_error: 'Доступ к репозиторию временно затруднён. Пожалуйста, обновите страницу или повторите попытку позже.',
		ontotext_wait: 'Репозиторий готовится для использования. Пожалуйста, подождите ещё несколько секунд или повторите попытку позже.'
	},
	ru : {
		tools : 'Инструменты',
		matadata : 'Метаданные',
		the_beta : 'Примеры работы с различными графами знаний',
		the_graph : 'Введите ключевые слова для поиска по графу знаний «',
		the_dbpedia : 'Лёгкая навигация по международным базам знаний Wikidata, DBpedia',
		the_start : 'Начать поиск \>\>',
		the_word : 'Слова для поиска ...',
		the_type : 'Тип',
		the_title : 'Наименование',
		the_url : 'Ссылка на ресурс',
		the_class : 'Класс',
		the_comment : 'Комментарий',
		the_keywords : 'Ключевые слова',
		the_property : 'Свойство',
		the_resource : 'Введите адрес ресурса',
		resource : 'Ресурс',
		no_classes : 'Классы не обнаружены',
		restart : 'Закрыть граф',
		generateInverse : 'Сгенерировать обратные отношения',
		autoExpand : 'Режим автоматического расширения',
		autoSameAs : 'Показывать связи между аналогичными сущностями',
		autoCollectImages : 'Собирать изображения в ходе поиска',
		autoDrawMap : 'Ресурсы геолокации',
		noName : 'Не указано наименование',
		addUri : 'Введите URI',
		findResource : 'Найти ресурсы',
		choose : 'Выберите ...',
		choose_class : 'Выберите концепт ...',
		resourceMissing : 'Ресурс не найден',
		resourceMissingDoc : 'Строковые данные или изображения не были обнаружены.',
		options : 'ОПЦИИ',
		endpointNotConfigured : 'Для ресурса не сконфигурирована точка доступа.',
		endpointNotConfiguredSoInternal : 'Для ресурса не сконфигурирована точка доступа, создание временного графа.',
		impostaUnaURI : 'Задайте URI, сформируйте поисковый запрос или выберите один из предложенных примеров.',
		example : 'Пример',
		noIe : 'Internet Explorer не поддерживается.',
		errorBox : 'Ошибка точки доступа',
		errorOntotext : 'Систематическая ошибка Ontotext GraphDB. Пожалуйста, попробуйте позже.',
		enpointNotAvailable : 'Ошибка точки доступа',
		enpointNotAvailableOrSLow : 'Ошибка точки доступа или превышен лимит времени.',
		imagesNotFound : 'Для ресурса не найдено изображений.',
		mapNotFound : 'Для ресурса не найдено карт.',
		propsNotFound : 'Ничего не найдено.',
		propsFound : 'Найденные свойства',
		showResource : 'Подсветить ресурс',
		zoomIn : 'Увеличить',
		showConsole : 'Показать консоль (experimental)',
		executeThisQuery : 'Выполнить SPARQL-запрос в новом окне',
		moreInfoOnThis : 'Больше информации об этом ресурсе',
		ontotextSearch : 'Семантическая паутина',
		simpleSearch : 'Поиск в Wikidata, DBpedia',
		endPoint : 'Выберите граф знаний',
		choose_graph : 'Выберите граф ...',
		ontotextSearchDescription : 'Облачная платформа Ontotext GraphDB и образовательный портал «Кафедра онлайн» предлагают вашему вниманию базу знаний, в которой можно осуществлять поиск ресурсов по ключевым словам.<br>Чтобы найти нужный ресурс, выберите подходящий граф знаний и начните вводить символы ключевого слова. Затем выберите подходящий ресурс из предложенного списка и нажмите "Начать поиск >>"',
		simpleSearchDescription : 'Wikidata и DBpedia есть крупнейшие международные база знаний, в которых можно осуществлять поиск ресурсов по ключевым словам.<br>Чтобы найти требуемый ресурс, в строке ввода наберите несколько первых букв ключевого слова. Затем выберите подходящий ресурс из предложенного списка и нажмите "Начать поиск >>"',
		insertUri : 'Простой поиск по URI',
		insertUriDescription : 'При помощи этого виджета возможно анализировать и отображать даже те RDF-ресурсы, которые по каким-либо причинам недоступны через SPARQL-запросы.<br/><br/>Указав URI произвольного RDF-ресурса, можно получить доступ к соответствующему контенту и исследовать его взаимосвязи.',
		insertData : 'Найти данные',
		centerClose : 'Сфокусироваться на ресурсе',
		openOnline : 'Онлайн доступ к ресурсу',
		openRelated : 'Посмотреть связанные ресурсы',
		removeResource : 'Удалить элемент',
		noImage:'Изображение не доступно',
		connectedResources:'связанных ресурсов',
		ontotext_error: 'Доступ к репозиторию временно затруднён. Пожалуйста, обновите страницу или повторите попытку позже.',
		ontotext_wait: 'Репозиторий готовится для использования. Пожалуйста, подождите ещё несколько секунд или повторите попытку позже.'
	}	
});

